cmake_minimum_required(VERSION 3.10)

project (TapeFilterGenerator)


IF(MSVC)
	SET(CMAKE_CXX_FLAGS           "${CMAKE_CXX_FLAGS} /D \"SAFESEH:NO\"")
	SET(CMAKE_EXE_LINKER_FLAGS    "${CMAKE_EXE_LINKER_FLAGS} /SAFESEH:NO")
	SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /SAFESEH:NO")
	SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /SAFESEH:NO")
endif()

set(CompilerFlags
        CMAKE_CXX_FLAGS
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_RELEASE
        CMAKE_C_FLAGS
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_RELWITHDEBINFO
		_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING 
        )

add_executable( TapeFilterGenerator  
                TapeFilterGenerator.cpp 
)

target_link_libraries(TapeFilterGenerator PUBLIC CPCCoreEmu )

install(TARGETS TapeFilterGenerator 
            RUNTIME DESTINATION "./TapeFilterGenerator"
            LIBRARY DESTINATION "./TapeFilterGenerator"
            ARCHIVE DESTINATION lib/static)

