language: cpp
dist: xenial
language: cpp
services:
  - xvfb

#limit to git depth to 1 because don't use any git command in this script
git:
  depth: 1
  
before_install:
#g++ 7
- echo 'Installing G++ 8'
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
- sudo apt-get install udev
- sudo apt-get install libudev-dev
- sudo apt-get install build-essential libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew-dev libjpeg-dev libsndfile1-dev libopenal-dev

install:
- sudo apt-get install -y gdb  # install gdb

install:
- sudo apt-get install -y gdb  # install gdb

before_script:
- ulimit -c unlimited -S       # enable core dumps

script:
# SugarConvTape
- echo 'Generating makefile'
- cmake . -DGENERATE_UNITTESTS=TRUE
- make all
- make install
- cd $TRAVIS_BUILD_DIR/bin/
- ./unitTests

after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
