version: '{build}'

branches:
  only:
  - master
  
image:
- Visual Studio 2017
- Ubuntu1804

configuration:
- Release   

platform:
- x86
- x64

install:
- git submodule update --init --recursive
- git submodule init 
- sh: |- 
    echo 'Update to gcc8'
    sudo update-alternatives --set gcc /usr/bin/gcc-8
  
before_build:
- cmd: |-
    if %platform%==x64 (    set CMAKE_GENERATOR="Visual Studio 15 2017 Win64" ) else (   set CMAKE_GENERATOR="Visual Studio 15 2017")   
    mkdir build
    cd build
    cmake --version
    echo %CMAKE_GENERATOR%
    cmake .. -G %CMAKE_GENERATOR%
- sh: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -D GENERATE_UNITTESTS=TRUE
    
build_script:
- cmd : |- 
    cmake --build . --config %configuration%
- sh: |-
    make all

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - CPCCoreEmu

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\UnitTests.exe'