name: MacOS

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_call:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on:  macOS-latest
          
    steps:
    - uses: actions/checkout@v3
          
    - name: Install Third Party
      run: |
        brew install openal-soft 
        brew reinstall freetype

    - name: Checkout submodules
      run: git submodule update --init --recursive 

    - name: Build & install
      run: |
        echo 'Generating makefile'
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make install
        ls -l
          
