name: Build_Windows

on:
  workflow_call:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
            
    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGENERATE_UNITTESTS=TRUE -DCMAKE_INSTALL_PREFIX=${{github.workspace}}\install -AWin32

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

    - name: Install
      # Build your program with the given configuration
      run: |
        cmake --install ${{github.workspace}}\build\UnitTests\Release
        dir ${{github.workspace}}\build\UnitTests\Release
        
    - name: Archive zip
      uses: actions/upload-artifact@v3
      with:
          name: CPCCore_Win
          path: |
            ${{github.workspace}}/build/UnitTests/Release/unitTests.exe
            ${{github.workspace}}/build/UnitTests/Release/TestConf.ini
            ${{github.workspace}}/build/UnitTests/Release/res/
            ${{github.workspace}}/build/UnitTests/Release/CONF/
            ${{github.workspace}}/build/UnitTests/Release/CART/
            ${{github.workspace}}/build/UnitTests/Release/ROM/
