name: Build Ubuntu

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Environement
      run: |
        sudo apt-get update
        sudo apt install qtbase5-dev --fix-missing
        sudo apt-get install libqt5websockets5-dev --fix-missing
        sudo apt-get install udev build-essential libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew-dev libjpeg-dev libxi-dev --fix-missing
        sudo apt-get install libxinerama-dev libxcursor-dev --fix-missing
        sudo apt-get install libudev-dev libglu1-mesa-dev libsecret-1-dev libnotify-dev --fix-missing
        sudo apt-get install checkinstall libtiff5-dev ubuntu-restricted-extras freeglut3 freeglut3-dev libcairo2-dev --fix-missing
        sudo apt-get install libgconf2-dev --fix-missing
        
    - name: Checkout submodules
      run: git submodule update --init --recursive 
      
    - name: Configure a build
      run: |
        echo 'Generating makefile'
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DGENERATE_UNITTESTS=TRUE
        make all
        ls -l
        
    - name: Install
      # Build your program with the given configuration
      run: |
        cmake --install ${{github.workspace}}/build
        ls -l

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: bin/unitTests.exe
