name: Test_Windows

on:
  workflow_run:
    workflows: [Build_Windows]
    types:
      - completed
      
jobs:
  on-success:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:    
    - name: Get build elements
      run: echo Get Build elemnt TODO
            
    - name: Test
      working-directory: ${{github.workspace}}\build
      run: bin\unitTests.exe
