name: Test_Ubuntu

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "develop" ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  call-workflow:
    uses:  ./.github/workflows/build_ubuntu.yml
    
  notify:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build_ubuntu.yml
          name: CPCCore_linux
          path: ${{github.workspace}}
          
      - name: Test
        working-directory: ${{github.workspace}}
        run: |
          xvfb-run --auto-servernum bin/unitTests
    
        
