name: Test_Windows

on:
  push:
    branches: [ "master", "develop" ]
  workflow_run:
    workflows: [Build_Windows]
    types:
      - completed
      
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  on-success:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:    
    - name: Get build elements
      run: echo Get Build elemnt TODO
            
    - name: Test
      working-directory: ${{github.workspace}}\build
      run: bin\unitTests.exe
