name: Test_Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "develop" ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  call-workflow:
    uses:  ./.github/workflows/build_windows.yml
    
  notify:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success            

      - name: Test
        working-directory: ${{github.workspace}}\build
        run: bin\unitTests.exe

