name: Test_Ubuntu

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "develop" ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  call-workflow:
    uses:  ./.github/workflows/build_ubuntu.yml
