name: Test_Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "develop" ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  test:
    runs-on: windows-latest
    steps:    
    - name: Launch build
      uses:  ./.github/workflows/build_windows.yml

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success            

    - name: Test
      working-directory: ${{github.workspace}}\build
      run: bin\unitTests.exe

