name: Test_Windows

on:
  workflow_run:
    workflows: [Build_Windows]
    types:
      - completed
      
jobs:
  on-success:
    runs-on: windows-latest
    
    steps:
    - name: Get build elements
      run: echo Get Build elemnt TODO
      
    - name: Test
      working-directory: ${{github.workspace}}\build
      run: bin\unitTests.exe
