name: Test_Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "develop" ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  call-workflow:
    uses:  ./.github/workflows/build_windows.yml
    
  notify:
    needs: call-workflow
    runs-on: windows-latest
    steps:
    
    
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build_windows.yml
          name: CPCCore_Win
          path: ${{github.workspace}}
          
      - name: Test
        working-directory: ${{github.workspace}}
        run: |
          cd CPCCore_Win
          bin\unitTests.exe

